sudo: enabled
dist: trusty
services:
- docker
before_install:
- docker build -t build-atomic $TRAVIS_BUILD_DIR/images/build
script:
- docker run 
  --privileged 
  --rm 
  -v $TRAVIS_BUILD_DIR:/manifests 
  -v $TRAVIS_BUILD_DIR/images/deploy/repo:/srv
  build-atomic
before_deploy:
  - git config --local user.name "Jonathan Bryant"
  - git config --local user.email "jonathan@videaris.com"
  - git tag "shire-atomic-$(date +'%Y%m%d%H')-$(git log --format=%h -1)"
deploy:
  provider: releases
  api_key: "$OAUTH"
  file: "$TRAVIS_BUILD_DIR/repo.tar.gz"
  skip_cleanup: true
  overwrite: true
